### PR TITLE
Add workflows

### PR DESCRIPTION
**Pull request by SlejmUr**
We want to able to build here. But not publish the projects.
.NET build could be done here, what do you think?

### CODE REVIEW

**Comment by pixelkingliam** [comment]
Can't say much as i haven't made use of Github Workflows

**Comment by SlejmUr** [comment]
Mainly asking the question that should we upload the compiled assemblies or not.

**Comment by pixelkingliam** [comment]
I think we should, since the game is going to be free anyways

**Comment by SlejmUr** [comment]
Nuget packages and DLLs will be uploaded
Did not added full build for godot yet. Do you want that?

**Comment by pixelkingliam** [comment]
I think we should have a godot build

**Comment by SlejmUr** [comment]
Godot Building cannot happen since it requires to use the Custom GodotTools build for using constants in export.
Other will be done and merged

**Pull request merged**
